title = "SYNNEX"
baseURL = "http://workshops.synnex.com"
theme = "redhatgov"
languageCode = "en-us"
metaDataFormat = "yaml"

[params]
    description = "Visibility Velocity Value"

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100
